### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by CMCDragonkai** [edolstra/nix-repl#28]
Now that nix-repl supports multiline expressions, I think it's a good time to add support for comments as well. So that when you copy multiline expressions that have comments, it doesn't message up the interpretation. It should be just like nix in files. With `# ... \n|$` identified as a comment.

**Comment by fkz** [comment]
what's your problem? For me, that already works.

**Comment by CMCDragonkai** [comment]
I get a syntax error for nix-repl 1.10. Try `# blah`.

**Comment by tsion** [comment]
@CMCDragonkai It's not an error in the latest version.
