### ISSUE TITLE
Feature request for a :c

### ISSUE THREAD

**Issue by CMCDragonkai** [edolstra/nix-repl#3]
Something that clears the screen.

Also I noticed that all the builtins are available as `__getEnv` instead of `builtins.getEnv`. Which one should I be using?

**Comment by tsion** [comment]
In my terminals I can use Ctrl-L to clear nix-repl (and many other programs).

I think `__getEnv` et al are implementation details. `builtins` is the standard way to access these.

**Comment by tsion** [comment]
For a point of comparison, GHCi also doesn't support a `:clear` command that I can see, but Ctrl-L works there, too. So I think we can close this issue.

@edolstra Would it make sense to filter out the variables beginning with `__` from tab completion? Or is there some other way to hide them?

**Comment by solson** [comment]
@CMCDragonkai Can you close this issue, given that Ctrl-L works?

**Comment by CMCDragonkai** [comment]
Doesn't CTRL-L rely on the terminal emulator?

**Comment by solson** [comment]
@CMCDragonkai Yes, and it works in every terminal emulator I've ever used, including Linux VTs and Windows cmd.exe. Like I said before, GHCi doesn't implement a clear command either, because Ctrl-L works basically everywhere.
