### ISSUE TITLE
Segmentation fault when using tarball in NIX_PATH

### ISSUE THREAD

**Issue by domenkozar** [edolstra/nix-repl#31]
```
$ NIX_PATH=nixpkgs=http://nixos.org/channels/nixos-16.03/nixexprs.tar.xz nix-shell -p nix-repl --run nix-repl
/run/user/499/nix-shell.ZX0UGk/rc: line 1: 15369 Segmentation fault      nix-repl

$ nix-build -A nix-repl '<nixpkgs>'
/nix/store/3f0k61j9kr5l99156m0s8ydx101yymwa-nix-repl-1.11.2-8a2f5f0
```

**Comment by solson** [comment]
This is the bug I fixed in https://github.com/edolstra/nix-repl/pull/18. I just confirmed I can't reproduce this segfault on nix-repl master.

**Comment by domenkozar** [comment]
Thank you!

Fixed in https://github.com/NixOS/nixpkgs/commit/5789f5875fc4f90058b67ae501fa0588c7e1e221 and https://github.com/NixOS/nixpkgs/commit/984e559cddbcf19566faf91d7b555015f63882e2
