### ISSUE TITLE
:l <nixos> doesn't load the same thing in 16.09 as it does in 16.03.

### ISSUE THREAD

**Issue by seanparsons** [edolstra/nix-repl#34]
Something has changed which it appears from a conversation in #nixos would imply that we actually want to load `<nixpkgs/nixos>` instead in 16.09 to get the config set and related fields.

```
# nix-repl
Welcome to Nix version 1.11.4. Type :? for help.

nix-repl> :l <nixos>
Added 6637 variables.

nix-repl> :l <nixpkgs>
Added 6637 variables.
```

**Comment by solson** [comment]
Why is this a nix-repl issue? Just to update the example in the README?

**Comment by domenkozar** [comment]
This hasn't changed much since nixos and nixpkgs git repo merge. `<nixos>` refers to nixos channel, which actually points to nixpkgs repository that contains `./nixos`.
