### ISSUE TITLE
Multiline repl

### ISSUE THREAD

**Issue by CMCDragonkai** [edolstra/nix-repl#4]
The current REPL doesn't seem to support expressions over multiple lines. This would make it easier to test how Nix understands an expression that has newlines in between certain areas.

**Comment by tsion** [comment]
To do this nicely, I think the expression parser would need a way to signal whether a parse is in error or simply "incomplete". In that case you would somehow tell readline to simply insert a newline in the input - I'm not sure how that works but the fish shell does it.

@edolstra Do you know if the Nix parser could do that?

Alternatively, we could make it always continue onto a new line on parse error (and cancel with Ctrl-C) but that's less friendly to new users.

**Comment by CMCDragonkai** [comment]
Surely we could do it similar to GHCi, basically once you enable multiline. An <kbd>enter</kbd> does not finish the expression. A double <kbd>enter</kbd> finishes the expression.

**Comment by tsion** [comment]
I thought the GHCi method was the `:{` and `:}` commands. Is there another way to enable multiline? (We could certainly do something like `:{` or what you described - I hadn't considered that.)

**Comment by CMCDragonkai** [comment]
That's an alternative multiline method. It's enabled using :set
something....

**Comment by tsion** [comment]
Ah, found it. It's `:set +m`: http://stackoverflow.com/a/13341505/1535283

**Comment by tsion** [comment]
@CMCDragonkai I submitted a PR (#21) based on my initial thoughts. It allows multiline input quite seamlessly, without any special modes.

**Comment by CMCDragonkai** [comment]
Awesome.
